### ISSUE TITLE
How to share a global spelling check dictionary, without bloating project file

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/team#141]

**Comment by K-Beicher** [comment]
I've done a bit of experimentation, and it looks like there are three main options, I will though need some help with testing the last details.

### First Option
Using Dropbox it is possible to share a folder/file. You can then add the folder/filename in the settings under CustomDictionary, this works on my machine, but I need to have someone else test it to see if they can add, and whether or not it will then show up here.

### Second Option
Same as above, but instead of adding a folder/file combo a raw.githubusercontent url is added, again, this seems to work here, but I need someone to test if it also works if someone else updates the file.

### Third Option
We create a cspell.json file in .github which is then shared with others. The only problem here is that we can't add to it, so this will need to be done manually from time to time.

Who's got a dropbox they can add to their laptop so that the file can be share?
Who's game for testing the raw.github solution?

**Comment by K-Beicher** [comment]
### Failed test of raw.github

There is a txt file on the main Seedcase repo, which is ready to play with.  I've checked that the link below leads to the file, but when I'm trying to add a word using the Quick Fix method I'm told I'm not allowed to write to the file.  

If anyone would like to play with this, then the code to enter is as follows:

 "cSpell.customDictionaries": {
        "project-words": {
            "name": "Dropbox-dictionary",
            "path": "/Users/au157729/Library/CloudStorage/Dropbox/Private/Work/Dictionary-GitHub/Seedcase-dictionary.txt",
            "description": "Words used across Seedcase",
            "addWords": true
        },
        "Git-words": {
            "name": "Git-dictionary",
            "path": "https://raw.githubusercontent.com/seedcase-project/seedcase/main/test-dictionary.txt",
            "description": "Words used across Seedcase",
            "addWords": true
        },
        "custom": true, // Enable the `custom` dictionary
        "internal-terms": false // Disable the `internal-terms` dictionary
    },

**Comment by K-Beicher** [comment]
### Test of Dropbox file

File is currently shared in edit mode with @lwjohnst86, the code above needs to be copied into settings.json (user version), and the path changed to wherever the file is located in the local file structure.

Then see if you are allowed to add new words (feel free to make up a few typos, we can clean it later).

**Comment by K-Beicher** [comment]
@signekb, @martonvago if you would like to take advantage of the shared Seedcase dictionary, then I'll need you to install Dropbox on your laptop (best to set it to not sync anything for now). I will also need the email I should use for inviting you to share the folder and file from my account.

Once the file Seedcase-dictionary.txt is shared with you, and you have set it to synchronise with your laptop, then finde the spell checker and add the following to the settings.

Open settings for Code Spell Checker and add/change the following settings (don't forget to change the path):

"cSpell.customDictionaries": {
        "project-words": {
            "name": "Seedcase-dictionary",
            "path": "/Users/au157729/Library/CloudStorage/Dropbox/Dictionary-GitHub/Seedcase-dictionary.txt",
            "description": "Words used across Seedcase",
            "addWords": true
        },
        "custom": true, // Enable the `custom` dictionary
        "internal-terms": false // Disable the `internal-terms` dictionary
    },

**Comment by signekb** [comment]
Amazing, @K-Beicher ! Will you invite me via my work email?

**Comment by K-Beicher** [comment]
@signekb, @martonvago you should have received invitations to share the folder, I'm 95% sure that if you add the code to the spell checker above you should be able to contribute words.  Feel free to let me know if you add something and I can check to see that it worked.

**Comment by signekb** [comment]
Wuhu, works for me 🎉
