### ISSUE TITLE
Review webpages and list all things that look weird or need improvement

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/team#142]
- decision
- main website
- community
- team
- design

**Comment by martonvago** [comment]
General comments:
* Design (colour scheme, layout, fonts etc.) should match Sprout’s (related: https://github.com/seedcase-project/seedcase-theme/issues/23, https://github.com/seedcase-project/seedcase-theme/issues/15)
* For all subpages (decisions, design, team etc.), I think it would be helpful to make it more explicit that they are subpages of the Seedcase project. It says it in the header (and the URL and there is a home button), but if I just stumbled upon a subpage, it wouldn’t be immediately obvious to me that there was a broader context/more to explore. Related (maybe): https://github.com/seedcase-project/seedcase-theme/issues/22.
* Blockquotes are sometimes used as emphasis (e.g. in decision posts to state the main question or [here](https://team.seedcase-project.org/user-tests/sprout) when describing what Sprout does). I think that this kind of achieves the opposite effect because the text is fainter. I’m also not sure if it’s semantically correct to use blockquotes like this?
* Make sidebars uniform across all subpages. The team page has the first section as the first item in the sidebar, but the community page has a link to the community page itself as the first item.
* Would it be useful to make the category tags clickable? On the one hand, currently they are a bit decorative because there is no way of seeing all posts under a given category (I think?) and they don’t show up in the search. On the other hand, having separate pages aggregating posts by category feels a bit overkill. Related: https://github.com/seedcase-project/decisions/issues/64.
* I found it a bit confusing at first that landing pages feature some sections listed in the sidebar but not all of them. I first assumed it was like one of those websites where the sidebar is for jumping to a section in the page body, and this made me miss some sections. But this may not be universal 😅 

Page-specific comments in separate issues:
* https://github.com/seedcase-project/seedcase-project/issues/241
* https://github.com/seedcase-project/community/issues/21
* https://github.com/seedcase-project/team/issues/146
* https://github.com/seedcase-project/design/issues/66
* https://github.com/seedcase-project/decisions/issues/64

**Comment by lwjohnst86** [comment]
Love your comment about the semantics of using blockquotes!! I personally have never really thought about them in how they semantically are used. So that's a great consideration. I guess just having a paragraph that is all italicized would work? Do you have suggestions on how to emphasize a block of text? Could be a generic callout block?

**Comment by martonvago** [comment]
My first thought was also a callout block with no special flavour - they look quite nice I think! But, depending on context, a sentence or two in italics or bold doesn't strike me as too horrible.

(I only thought of the semantics of it because I think someone mentioned accessibility the other day, and I guess correct use of HTML tags is also an accessibility thing.)
